apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: littlepassports-efs-csi-restart
  title: Restart Stuck EFS-CSI Pods in Littlepassports Cluster
  description: This template Restarts Stuck EFS-CSI Pods in Littlepassports Cluster
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: group:devops
  type: service

  steps:
    - id: github-action
      name: Trigger GitHub Action
      action: github:actions:dispatch
      input:
        workflowId: littlepassports-efs-csi-restart.yml
        repoUrl: "github.com?repo=github-actions-and-crons&owner=LearnWithHomer"
        branchOrTagName: "master"
