site_name: Backstage Templates
# site_description: ${{values.description}}

nav:
  - Template Usage: index.md
  - Template Setup: 02-Setting-up-a-Backstage-Template.md

plugins:
  - techdocs-core

theme:
  name: material
  font: false
