name: Manage EC2 Instance

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (apply/destroy)'
        required: true

env:
  TFPATH: 'simple-ec2-template/infrastructure'

jobs:
  apply_instance:
    runs-on: self-hosted
    if: ${{ github.event.inputs.action == 'apply' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.TFPATH}}

    - name: Terraform Format
      run: terraform fmt
      working-directory: ${{env.TFPATH}}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{env.TFPATH}}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{env.TFPATH}}

  destroy_instance:
    runs-on: self-hosted
    if: ${{ github.event.inputs.action == 'destroy' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.TFPATH}}

    - name: Terraform FMT
      run: terraform fmt
      working-directory: ${{env.TFPATH}}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{env.TFPATH}}
      
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ${{env.TFPATH}}